version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    environment:
      POSTGRES_DB: geospatial_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql369
    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: psql369
      DB_NAME: geospatial_data
      DB_HOST: 192.168.0.101
      DB_PORT: 5431
      DATABASE_URL: postgres://postgres:psql369@192.168.0.101:5431/geospatial_data
    volumes:
      - .:/app
    command: >
      sh -c "
       python ingest_geojson.py &&
       uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
